# Generated by Django 4.2.17 on 2025-01-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scoopreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scoopreview',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scoopreview',
            name='blurb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
