# Generated by Django 4.2.17 on 2025-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoopreview',
            name='blurb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
