# Generated by Django 4.2.17 on 2025-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_scoopreview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
