# Generated by Django 4.2.17 on 2025-01-16 17:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_scoopreview_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoopreview',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
    ]
