# Generated by Django 4.2.17 on 2025-01-16 21:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_scoopreview_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoopreview',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder01', max_length=255, verbose_name='image'),
        ),
    ]
