# Generated by Django 4.2.17 on 2025-01-16 21:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_scoopreview_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoopreview',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dcaygv4vw/16aa550b58d759f1cd894bc2993d80a1/default_image', max_length=255, verbose_name='image'),
        ),
    ]
