# Generated by Django 4.2.17 on 2025-01-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_scoopreview_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='upvotes',
        ),
    ]
