# Generated by Django 4.2.17 on 2025-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_remove_reviewcomment_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoopreview',
            name='directions',
            field=models.URLField(blank=True, help_text='Map URL goes here', max_length=2000, null=True, unique=True),
        ),
    ]
