# Generated by Django 4.2.17 on 2025-01-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboraterequest_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='sent_at',
        ),
    ]
